version:  '3.2'
services:
  zookeeper:
    image: "confluent/zookeeper"
    networks:
      - microprofile
    ports:
      - 2181:2181
  kafka:
    image: "confluent/kafka"
    networks:
      - microprofile
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper
  schema-registry:
    image: "confluent/schema-registry"
    networks:
      - microprofile
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=none
    depends_on:
      - kafka
  rest-proxy:
    image: "confluent/rest-proxy"
    networks:
      - microprofile
    ports:
      - 8082:8082
    depends_on:
      - schema-registry
networks:
    microprofile:
